# Generated by Django 4.2.4 on 2023-09-02 06:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[6-9]{1}\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=8, null=True),
        ),
    ]
