# Generated by Django 4.2.4 on 2023-09-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_buyerprofile_address_alter_location_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.location'),
        ),
    ]
