# Generated by Django 4.2.4 on 2023-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(blank=True, choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=8, null=True),
        ),
    ]
