# Generated by Django 4.2.4 on 2023-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_sellerprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='userType',
        ),
        migrations.AddField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BuyerProfile',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
